### ISSUE TITLE
Waiting board data WE NEED YOU @Edouard127

### ISSUE THREAD

**Issue by urkoperez16** [Edouard127/reddit-placebot-2023#70] opened 2023-07-24 00:31 UTC

**Comment by SuperPou1** [comment] 2023-07-24 00:35
FOR REAL

**Comment by LucasMucaz** [comment] 2023-07-24 00:37
@Edouard127  @Edouard127  @Edouard127  @Edouard127

**Comment by Edouard127** [comment] 2023-07-24 01:22
```
func (b *Board) WaitForData() {
	for b.RequiredData == nil || b.CurrentData == nil {
	}
}

Shouldn't have any issues

**Comment by SuperPou1** [comment] 2023-07-24 01:29
> ```
> func (b *Board) WaitForData() {
> 	for b.RequiredData == nil || b.CurrentData == nil {
> 	}
> }
> 
> Shouldn't have any issues
> ```

it doesnt work tho

**Comment by urkoperez16** [comment] 2023-07-24 01:34
How do you ejecute? I am in Windows

**Comment by SuperPou1** [comment] 2023-07-24 01:35
> How do you ejecute? I am in Windows

dud that code doesn't mean anything, its literally the same as it already is

**Comment by urkoperez16** [comment] 2023-07-24 01:37
Oh, I have had false illusions

**Comment by futureguy11** [comment] 2023-07-24 01:38
Doesn't work for me as well..

**Comment by futureguy11** [comment] 2023-07-24 01:41
Doesn't work for me as well..

**_Login finished!
Waiting for board data_**

Stuck on this.

**Comment by urkoperez16** [comment] 2023-07-24 01:47
we are all in same part ![image](https://github.com/Edouard127/reddit-placebot-2023/assets/105135600/8894e848-4853-4540-8629-72c6077a36fa)

**Comment by urkoperez16** [comment] 2023-07-24 01:48
now put me "Error receiving message from socket EOF"

**Comment by declanht** [comment] 2023-07-24 01:50
I have Go 1.20.6 installed, and confirmed version in cmd
Go modules are installed, and an exception has been made in Windows Defender for leakless.exe
Tor Expert Bundle is unzipped and installed
torrc file (no extension) is correctly pointed to Tor (it refers to it on running tor.exe)
Tor.exe is properly pointed to PATH, checked in PowerShell with $env:PATH
User accounts and passwords copied and saved to users.json (no formatting issues)
The image.bmp is properly created and saved in "images" folder
I then run the redditplacebot.exe from its source in cmd with my minX and minY parameters

User login is confirmed successful, but then hangs on "waiting for board data..."

I initially ran the program without tor.exe running, and noticed the application was referring to X and Y values that were way off what I set as my parameters.

So I agree with one of the above comments that mentions that the canvas update on r/place has not been amended in this code Edouard has provided, thus leaving us stuck at waiting for board

Hope to see an update/response soon

**Comment by futureguy11** [comment] 2023-07-24 01:55
> now put me "Error receiving message from socket EOF"

That's probably because you're not running tor. I know because that just happened to me. Running tor fixes the issue.

The "Waiting for board data" error still persists, however.

**Comment by urkoperez16** [comment] 2023-07-24 01:59
if @Edouard127 update something, report here please

**Comment by LucasMucaz** [comment] 2023-07-24 02:11
@Edouard127 place has gotten larger

**Comment by Edouard127** [comment] 2023-07-24 02:14
There an issue reading the json data
For some reason the canvas info is incomplete, so It cannot unmarshal the json

**Comment by urkoperez16** [comment] 2023-07-24 02:17
don't worry, we wait

**Comment by declanht** [comment] 2023-07-24 02:18
> There an issue reading the json data For some reason the canvas info is incomplete, so It cannot unmarshal the json

The canvas expanded again ten minutes ago, is this perhaps the reason why?

**Comment by LucasMucaz** [comment] 2023-07-24 02:22
@Edouard127

**Comment by urkoperez16** [comment] 2023-07-24 02:23
let's see if we have any luck

**Comment by LeSunset** [comment] 2023-07-24 02:23
> > now put me "Error receiving message from socket EOF"
> 
> That's probably because you're not running tor. I know because that just happened to me. Running tor fixes the issue.
> 
> The "Waiting for board data" error still persists, however.

im running tor and get this error anyway

**Comment by urkoperez16** [comment] 2023-07-24 02:24
do you have path?

**Comment by LucasMucaz** [comment] 2023-07-24 02:26
are you actively fixing this @Edouard127

**Comment by Edouard127** [comment] 2023-07-24 02:29
https://github.com/golang/go/issues/2134

**Comment by LeSunset** [comment] 2023-07-24 02:30
> I just got it too, I guess it's normal at this time.

The PATH ist added and I started tor.exe manually. I already got this error before the board problems. Only 3 accounts work without an error, than some "Error receiving message from socket EOF" and after this the accounts start getting this error "Error receiving message from socket read tcp 10.59.108.3:59872->54.237.5.177:443: wsarecv"

**Comment by QvixoteRoux** [comment] 2023-07-24 02:36
> [golang/go#2134](https://github.com/golang/go/issues/2134)

So this is a direct issue with GO?

**Comment by urkoperez16** [comment] 2023-07-24 02:36
> > I just got it too, I guess it's normal at this time.
> 
> The PATH ist added and I started tor.exe manually. I already got this error before the board problems. Only 3 accounts work without an error, the first few accounts after that get this error: "Error receiving message from socket EOF" and after this the accounts start getting this error "Error receiving message from socket read tcp 10.59.108.3:59872->54.237.5.177:443: wsarecv: An existing connection was software controlled aborted by the host computer."
> 
> The accounts login tho and they get fully added to the json. But it doesn't feels right. Idk if they really work at the end

first let's fix "waiting board data" and then continue with that.

**Comment by LucasMucaz** [comment] 2023-07-24 02:51
> [golang/go#2134](https://github.com/golang/go/issues/2134)

explain????

**Comment by Edouard127** [comment] 2023-07-24 03:12
1521c71

**Comment by urkoperez16** [comment] 2023-07-24 03:13
YEEEEES

**Closed by Edouard127** 2023-07-24 03:12 UTC

**Comment by LucasMucaz** [comment] 2023-07-24 03:13
> [1521c71](https://github.com/Edouard127/reddit-placebot-2023/commit/1521c71ddaa6414949df85aafd003951c1f522a8)

i dont fully understand golang please explain in words

**Comment by LeSunset** [comment] 2023-07-24 03:20
> YEEEEES

is it working for you? I get tons of errors

**Comment by declanht** [comment] 2023-07-24 03:26
> [1521c71](https://github.com/Edouard127/reddit-placebot-2023/commit/1521c71ddaa6414949df85aafd003951c1f522a8)

I have updated the 6 files, rebooted and restarted Tor and run the commands again

How long does it typically take to get the board data?

I'm just going to let it run for now and see what happens, thanks for all your hard work in the meantime
